import { RouteCheckpoint, WhatIfScenario, WeatherData } from '../types';

export const getWhatIfScenarios = (baseWeather: WeatherData): WhatIfScenario[] => {
  return [
    {
      slotKey: 'now',
      departureLabel: 'Abhi Niklu (Leave Now)',
      timeSubtitle: 'Current window: 06:15 PM',
      rainProbability: baseWeather.rainProbability || 45,
      temperature: baseWeather.temperature,
      windSpeed: baseWeather.windSpeed,
      delayMins: '+8 mins',
      delayRisk: 'Low',
      waterloggingSeverity: 'Low (Surface wet, underpasses clear)',
      lightningHazard: 'Isolated (Low risk)',
      summary: 'Storm cell is still 18 km southwest. Corridors are wet but open with nominal traffic velocity.',
      actionRecommendation: 'Recommended departure window. Depart within next 20 mins to bypass heavy convective downpours.',
      verdictBadge: 'RECOMMENDED: BEST WINDOW',
      isRecommended: true,
    },
    {
      slotKey: '7pm',
      departureLabel: 'Sham 7:00 PM (Wait +45m)',
      timeSubtitle: 'Peak squall window: 07:00 PM',
      rainProbability: Math.min(96, Math.max(85, (baseWeather.rainProbability || 45) + 35)),
      temperature: baseWeather.temperature - 2,
      windSpeed: (baseWeather.windSpeed || 20) + 18,
      delayMins: '+45 mins delay',
      delayRisk: 'High',
      waterloggingSeverity: 'Severe (> 1.2 ft in low-lying underpasses)',
      lightningHazard: 'Severe (Frequent cloud-to-ground strikes)',
      summary: 'Heavy convective squall cell arriving overhead. High risk of waterlogging, crawling traffic, and low visibility.',
      actionRecommendation: 'Avoid transit. Heavy waterlogging expected at underpasses and key intersections; shift to Metro or wait inside shelter.',
      verdictBadge: 'AVOID DEPARTURE: SEVERE RISK',
      isRecommended: false,
    },
    {
      slotKey: '9pm',
      departureLabel: 'Raat 9:30 PM (Wait +3h)',
      timeSubtitle: 'Post-storm window: 09:30 PM',
      rainProbability: 25,
      temperature: baseWeather.temperature - 3,
      windSpeed: 14,
      delayMins: '+5 mins',
      delayRisk: 'Low',
      waterloggingSeverity: 'Receding (Pumps active, water clearing)',
      lightningHazard: 'Dissipated (Safe)',
      summary: 'Rain clouds moving eastward. Municipal drainage pumps clearing road ponding; smooth transit flow.',
      actionRecommendation: 'Safe delayed transit window. Roadways drained and vehicular traffic returned to normal pace.',
      verdictBadge: 'SAFE DELAYED WINDOW',
      isRecommended: false,
    },
    {
      slotKey: 'tomorrow',
      departureLabel: 'Kal Subah (Tomorrow 07:30 AM)',
      timeSubtitle: 'Next day: 07:30 AM',
      rainProbability: 10,
      temperature: 24,
      windSpeed: 10,
      delayMins: '0 mins (On-time)',
      delayRisk: 'Low',
      waterloggingSeverity: 'None (Completely dry corridors)',
      lightningHazard: 'Zero risk',
      summary: 'Clear morning skies with pleasant ambient temperatures and dry national highway corridors.',
      actionRecommendation: 'Best overall choice if travel is non-urgent. Maximum fuel economy and comfortable driving conditions.',
      verdictBadge: 'OPTIMAL NON-URGENT DEPARTURE',
      isRecommended: false,
    }
  ];
};

export const POPULAR_ROUTES = [
  { 
    id: 'delhi-gurugram',
    name: 'Delhi-Gurugram Expressway',
    origin: 'Connaught Place, Central Delhi', 
    destination: 'Cyber City, Gurugram',
    totalDistanceKm: 31.4,
    estimatedDurationMins: 58,
    corridorTag: 'High Commute Density'
  },
  { 
    id: 'noida-airport',
    name: 'Airport Express Corridor',
    origin: 'Noida Electronic City, Sec 62', 
    destination: 'IGI Airport Terminal 3',
    totalDistanceKm: 38.2,
    estimatedDurationMins: 65,
    corridorTag: 'Critical Transit Link'
  },
  { 
    id: 'delhi-karnal',
    name: 'Grand Trunk Agri Corridor (NH-44)',
    origin: 'New Delhi Railway Station', 
    destination: 'Karnal Agri Hub (NH-44)',
    totalDistanceKm: 128.0,
    estimatedDurationMins: 145,
    corridorTag: 'Interstate Freight & Agro'
  },
  { 
    id: 'pune-hinjawadi',
    name: 'Pune IT Park Expressway',
    origin: 'Pune Station', 
    destination: 'Hinjawadi IT Park',
    totalDistanceKm: 19.8,
    estimatedDurationMins: 45,
    corridorTag: 'Tech Corridor'
  },
];

export const calculateRouteWeather = (
  origin: string,
  destination: string
): { 
  checkpoints: RouteCheckpoint[]; 
  totalDistanceKm: number; 
  estimatedDurationMins: number; 
  routeAlert?: string;
  highestRiskCheckpoint?: string;
  safeDepartureAdvisory: string;
} => {
  const normOrigin = (origin || '').toLowerCase();
  const normDest = (destination || '').toLowerCase();

  // CORRIDOR 2: Noida to Airport
  if (normOrigin.includes('noida') || normDest.includes('airport') || normDest.includes('igi')) {
    return {
      totalDistanceKm: 38.2,
      estimatedDurationMins: 65,
      routeAlert: '⚠️ River Crosswind & Underpass Alert: Heavy convective cell near DND Flyway Yamuna Bridge (Wind 44 km/h) and AIIMS Underpass.',
      highestRiskCheckpoint: 'DND Flyway Yamuna Bridge & AIIMS Underpass',
      safeDepartureAdvisory: 'Maintain safe braking distance on flyways; avoid low-lying underpasses during heavy shower peaks.',
      checkpoints: [
        {
          id: 'cp-no-1',
          name: origin || 'Noida Electronic City, Sec 62',
          distanceKm: 0,
          eta: '00 mins',
          temperature: 32,
          condition: 'Passing Drizzle & Overcast',
          conditionCode: 'rain',
          rainProbability: 55,
          windSpeed: 20,
          visibilityKm: 4.8,
          roadWaterLevel: 'Wet surface',
          safeTransitAdvice: 'Normal transit speed permitted; wipers on low',
          corridorStatus: 'clear',
          isHazardous: false,
        },
        {
          id: 'cp-no-2',
          name: 'Akshardham NH-9 Elevated Flyover',
          distanceKm: 8.4,
          eta: '+14 mins',
          temperature: 31,
          condition: 'Breezy & Light Showers',
          conditionCode: 'rain',
          rainProbability: 68,
          windSpeed: 28,
          visibilityKm: 3.5,
          roadWaterLevel: 'Light spray',
          safeTransitAdvice: 'Elevated crosswinds; two-wheelers maintain lane center',
          corridorStatus: 'caution',
          isHazardous: false,
        },
        {
          id: 'cp-no-3',
          name: 'DND Flyway Yamuna Bridge',
          distanceKm: 17.1,
          eta: '+28 mins',
          temperature: 29,
          condition: 'Heavy Downpour & Severe Crosswinds',
          conditionCode: 'thunderstorm',
          rainProbability: 90,
          windSpeed: 44,
          hazardNote: '⚠️ High crosswind gusts 44 km/h & reduced river visibility (< 1.8 km)',
          visibilityKm: 1.8,
          roadWaterLevel: 'Sheet flow on asphalt',
          safeTransitAdvice: 'Cap vehicular speed at 50 km/h; use hazard indicators in squall bursts',
          corridorStatus: 'danger',
          isHazardous: true,
        },
        {
          id: 'cp-no-4',
          name: 'AIIMS & Moti Bagh Underpasses',
          distanceKm: 26.3,
          eta: '+44 mins',
          temperature: 30,
          condition: 'Moderate Rain Showers',
          conditionCode: 'rain',
          rainProbability: 78,
          windSpeed: 30,
          hazardNote: 'Water ponding 4-6 inches detected near underpass entrance',
          visibilityKm: 2.5,
          roadWaterLevel: 'Ponding 4-6 inches',
          safeTransitAdvice: 'Stick to center lanes; do not stop under underpass',
          corridorStatus: 'caution',
          isHazardous: true,
        },
        {
          id: 'cp-no-5',
          name: destination || 'IGI Airport Terminal 3',
          distanceKm: 38.2,
          eta: '+65 mins',
          temperature: 29,
          condition: 'Overcast & Moderate Drizzle',
          conditionCode: 'rain',
          rainProbability: 72,
          windSpeed: 24,
          visibilityKm: 3.8,
          roadWaterLevel: 'Draining smoothly',
          safeTransitAdvice: 'Airport approach ramps clear; departures operating on schedule',
          corridorStatus: 'clear',
          isHazardous: false,
        },
      ]
    };
  }

  // CORRIDOR 3: Delhi to Karnal (Agri corridor)
  if (normOrigin.includes('karnal') || normDest.includes('karnal') || normDest.includes('nh-44') || normDest.includes('panipat')) {
    return {
      totalDistanceKm: 128.0,
      estimatedDurationMins: 145,
      routeAlert: '🌾 Agro Corridor Weather Advisory: Active monsoon trough crossing NH-44 between Sonepat and Panipat. High spray on asphalt.',
      highestRiskCheckpoint: 'Panipat Elevated Highway & Murthal Bypass',
      safeDepartureAdvisory: 'Truckers and freight carriers should secure open cargo tarpaulins against wind gusts.',
      checkpoints: [
        {
          id: 'cp-kn-1',
          name: origin || 'New Delhi Railway Station',
          distanceKm: 0,
          eta: '00 mins',
          temperature: 31,
          condition: 'Overcast Skies',
          conditionCode: 'cloudy',
          rainProbability: 60,
          windSpeed: 22,
          visibilityKm: 4.5,
          roadWaterLevel: 'Dry to damp',
          safeTransitAdvice: 'City exit clear; normal expressway entry',
          corridorStatus: 'clear',
          isHazardous: false,
        },
        {
          id: 'cp-kn-2',
          name: 'Singhu Border (Delhi-Haryana Node)',
          distanceKm: 28.5,
          eta: '+38 mins',
          temperature: 30,
          condition: 'Heavy Monsoon Rain Showers',
          conditionCode: 'rain',
          rainProbability: 84,
          windSpeed: 32,
          visibilityKm: 2.8,
          roadWaterLevel: 'Surface water spray',
          safeTransitAdvice: 'Toll bottleneck; stay in fastag lane to avoid standing shoulder water',
          corridorStatus: 'caution',
          isHazardous: false,
        },
        {
          id: 'cp-kn-3',
          name: 'Murthal & Sonepat Bypass',
          distanceKm: 54.2,
          eta: '+68 mins',
          temperature: 29,
          condition: 'Convective Rain & Lightning',
          conditionCode: 'thunderstorm',
          rainProbability: 89,
          windSpeed: 38,
          hazardNote: 'Frequent cloud lightning; highway spray reduces overtaking sight distance',
          visibilityKm: 2.0,
          roadWaterLevel: 'Wet asphalt; puddle pockets',
          safeTransitAdvice: 'Keep low-beam headlights on; maintain 100m inter-vehicle gap',
          corridorStatus: 'danger',
          isHazardous: true,
        },
        {
          id: 'cp-kn-4',
          name: 'Panipat Elevated Highway (NH-44)',
          distanceKm: 88.7,
          eta: '+105 mins',
          temperature: 29,
          condition: 'Gusty Rain Squalls',
          conditionCode: 'rain',
          rainProbability: 82,
          windSpeed: 40,
          hazardNote: 'Elevated crosswind corridor; high-sided commercial vehicles slow down',
          visibilityKm: 2.5,
          roadWaterLevel: 'Elevated deck draining',
          safeTransitAdvice: 'Hold steering firmly on flyover deck against crosswind gusts',
          corridorStatus: 'danger',
          isHazardous: true,
        },
        {
          id: 'cp-kn-5',
          name: destination || 'Karnal Agri Hub (NH-44)',
          distanceKm: 128.0,
          eta: '+145 mins',
          temperature: 28,
          condition: 'Moderate Rain & Agricultural Mist',
          conditionCode: 'rain',
          rainProbability: 74,
          windSpeed: 20,
          visibilityKm: 4.0,
          roadWaterLevel: 'Agri ditches flowing',
          safeTransitAdvice: 'Mandi arrival roads clear; covered shed parking recommended',
          corridorStatus: 'clear',
          isHazardous: false,
        },
      ]
    };
  }

  // CORRIDOR 4: Pune to Hinjawadi
  if (normOrigin.includes('pune') || normDest.includes('hinjawadi') || normDest.includes('wakad')) {
    return {
      totalDistanceKm: 19.8,
      estimatedDurationMins: 45,
      routeAlert: '🌧️ Western Ghats Cloud Belt Alert: Heavy drizzle along Aundh flyover & Wakad bypass. Wet road friction reduced.',
      highestRiskCheckpoint: 'Wakad Highway Bypass & Aundh Flyover',
      safeDepartureAdvisory: 'Two-wheeler commuters should wear protective rain gear; avoid sharp banking on wet flyover turns.',
      checkpoints: [
        {
          id: 'cp-pn-1',
          name: origin || 'Pune Railway Station',
          distanceKm: 0,
          eta: '00 mins',
          temperature: 26,
          condition: 'Intermittent Drizzle',
          conditionCode: 'rain',
          rainProbability: 52,
          windSpeed: 16,
          visibilityKm: 5.0,
          roadWaterLevel: 'Damp surface',
          safeTransitAdvice: 'Urban traffic flowing at normal speeds',
          corridorStatus: 'clear',
          isHazardous: false,
        },
        {
          id: 'cp-pn-2',
          name: 'Shivajinagar IMD Observatory Node',
          distanceKm: 5.3,
          eta: '+12 mins',
          temperature: 26,
          condition: 'Overcast & Dense Mist',
          conditionCode: 'cloudy',
          rainProbability: 60,
          windSpeed: 18,
          visibilityKm: 3.5,
          roadWaterLevel: 'Wet roads',
          safeTransitAdvice: 'Visibility good; minor traffic slowing near metro work',
          corridorStatus: 'clear',
          isHazardous: false,
        },
        {
          id: 'cp-pn-3',
          name: 'Aundh Flyover & Mula River Corridor',
          distanceKm: 11.8,
          eta: '+25 mins',
          temperature: 25,
          condition: 'Heavy Rain Showers',
          conditionCode: 'rain',
          rainProbability: 80,
          windSpeed: 28,
          hazardNote: 'River mist and wet flyover expansion joints causing slippage',
          visibilityKm: 2.2,
          roadWaterLevel: 'Wet asphalt; slippery joints',
          safeTransitAdvice: 'Avoid sudden braking on metal expansion joints',
          corridorStatus: 'caution',
          isHazardous: true,
        },
        {
          id: 'cp-pn-4',
          name: 'Wakad Mumbai-Bangalore Highway Bypass',
          distanceKm: 15.9,
          eta: '+36 mins',
          temperature: 25,
          condition: 'Gusty Rain & Spray',
          conditionCode: 'rain',
          rainProbability: 84,
          windSpeed: 32,
          hazardNote: 'Highway merge bottleneck with low visibility',
          visibilityKm: 2.0,
          roadWaterLevel: 'Heavy surface spray',
          safeTransitAdvice: 'Merge with caution; truck spray high in right lanes',
          corridorStatus: 'danger',
          isHazardous: true,
        },
        {
          id: 'cp-pn-5',
          name: destination || 'Hinjawadi IT Park Phase 1',
          distanceKm: 19.8,
          eta: '+45 mins',
          temperature: 25,
          condition: 'Light Showers & Pleasant',
          conditionCode: 'rain',
          rainProbability: 66,
          windSpeed: 18,
          visibilityKm: 4.2,
          roadWaterLevel: 'Paved campus drainage clear',
          safeTransitAdvice: 'IT campus gates and podium parking fully accessible',
          corridorStatus: 'clear',
          isHazardous: false,
        },
      ]
    };
  }

  // DEFAULT / CORRIDOR 1: Delhi NCR to Gurugram (Delhi-Gurugram Expressway)
  return {
    totalDistanceKm: 31.4,
    estimatedDurationMins: 58,
    routeAlert: '⛈️ Corridor Convective Alert: Heavy thunderstorm cell detected between km 15–22 (Aerocity Underpass to Sirhaul Border). Underpass flooding risk.',
    highestRiskCheckpoint: 'Mahipalpur / Aerocity Underpass (km 18.5)',
    safeDepartureAdvisory: 'If travelling within next 30 mins, divert to elevated flyover or rapid metro corridor to bypass underpass congestion.',
    checkpoints: [
      {
        id: 'cp-1',
        name: origin || 'Connaught Place, Central Delhi',
        distanceKm: 0,
        eta: '00 mins',
        temperature: 31,
        condition: 'Overcast & Drizzle',
        conditionCode: 'rain',
        rainProbability: 65,
        windSpeed: 22,
        visibilityKm: 4.0,
        roadWaterLevel: 'Wet asphalt; light spray',
        safeTransitAdvice: 'City exit clear; normal expressway entry',
        corridorStatus: 'clear',
        isHazardous: false,
      },
      {
        id: 'cp-2',
        name: 'Dhaula Kuan Junction Flyover',
        distanceKm: 9.2,
        eta: '+18 mins',
        temperature: 30,
        condition: 'Heavy Downpour',
        conditionCode: 'rain',
        rainProbability: 85,
        windSpeed: 34,
        hazardNote: 'Caution: Slow-moving traffic & gusty crosswinds on flyover',
        visibilityKm: 2.8,
        roadWaterLevel: 'Moderate road spray',
        safeTransitAdvice: 'Slow down on flyover curve; two-wheelers watch side winds',
        corridorStatus: 'caution',
        isHazardous: true,
      },
      {
        id: 'cp-3',
        name: 'Mahipalpur / Aerocity Underpass',
        distanceKm: 18.5,
        eta: '+34 mins',
        temperature: 29,
        condition: 'Intense Rain & Low Visibility',
        conditionCode: 'thunderstorm',
        rainProbability: 92,
        windSpeed: 38,
        hazardNote: '⚠️ Water pooling > 1.2 ft alert near underpass exit ramp; visibility < 1.8 km',
        visibilityKm: 1.8,
        roadWaterLevel: 'Ponding > 1.2 ft in lower ramp',
        safeTransitAdvice: 'Take upper flyover lane; avoid lower underpass service lane',
        corridorStatus: 'danger',
        isHazardous: true,
      },
      {
        id: 'cp-4',
        name: 'Sirhaul Border (Delhi-Haryana Toll)',
        distanceKm: 24.8,
        eta: '+46 mins',
        temperature: 30,
        condition: 'Moderate Rain Showers',
        conditionCode: 'rain',
        rainProbability: 78,
        windSpeed: 28,
        hazardNote: 'Toll bottleneck; road surface wet but draining smoothly',
        visibilityKm: 3.2,
        roadWaterLevel: 'Draining smoothly',
        safeTransitAdvice: 'Keep safe distance at toll boom barrier approach',
        corridorStatus: 'caution',
        isHazardous: false,
      },
      {
        id: 'cp-5',
        name: destination || 'Cyber City, Gurugram',
        distanceKm: 31.4,
        eta: '+58 mins',
        temperature: 30,
        condition: 'Light Rain & Overcast',
        conditionCode: 'rain',
        rainProbability: 70,
        windSpeed: 24,
        visibilityKm: 4.5,
        roadWaterLevel: 'Paved business district drainage clear',
        safeTransitAdvice: 'Destination approach normal; sheltered basement parking accessible',
        corridorStatus: 'clear',
        isHazardous: false,
      },
    ],
  };
};
