import { RouteCheckpoint, WhatIfScenario, WeatherData } from '../types';

export const getWhatIfScenarios = (baseWeather: WeatherData): WhatIfScenario[] => {
  return [
    {
      slotKey: 'now',
      departureLabel: 'Abhi Niklu (Leave Now)',
      timeSubtitle: 'Current window: 06:15 PM',
      rainProbability: baseWeather.rainProbability || 45,
      temperature: baseWeather.temperature,
      windSpeed: baseWeather.windSpeed,
      delayMins: '+8 mins',
      delayRisk: 'Low',
      waterloggingSeverity: 'Low (Surface wet, underpasses clear)',
      lightningHazard: 'Isolated (Low risk)',
      summary: 'Storm cell is still 18 km southwest. Corridors are wet but open with nominal traffic velocity.',
      actionRecommendation: 'Recommended departure window. Depart within next 20 mins to bypass heavy convective downpours.',
      verdictBadge: 'RECOMMENDED: BEST WINDOW',
      isRecommended: true,
    },
    {
      slotKey: '7pm',
      departureLabel: 'Sham 7:00 PM (Wait +45m)',
      timeSubtitle: 'Peak squall window: 07:00 PM',
      rainProbability: Math.min(96, Math.max(85, (baseWeather.rainProbability || 45) + 35)),
      temperature: baseWeather.temperature - 2,
      windSpeed: (baseWeather.windSpeed || 20) + 18,
      delayMins: '+45 mins delay',
      delayRisk: 'High',
      waterloggingSeverity: 'Severe (> 1.2 ft in low-lying underpasses)',
      lightningHazard: 'Severe (Frequent cloud-to-ground strikes)',
      summary: 'Heavy convective squall cell arriving overhead. High risk of waterlogging, crawling traffic, and low visibility.',
      actionRecommendation: 'Avoid transit. Heavy waterlogging expected at underpasses and key intersections; shift to Metro or wait inside shelter.',
      verdictBadge: 'AVOID DEPARTURE: SEVERE RISK',
      isRecommended: false,
    },
    {
      slotKey: '9pm',
      departureLabel: 'Raat 9:30 PM (Wait +3h)',
      timeSubtitle: 'Post-storm window: 09:30 PM',
      rainProbability: 25,
      temperature: baseWeather.temperature - 3,
      windSpeed: 14,
      delayMins: '+5 mins',
      delayRisk: 'Low',
      waterloggingSeverity: 'Receding (Pumps active, water clearing)',
      lightningHazard: 'Dissipated (Safe)',
      summary: 'Rain clouds moving eastward. Municipal drainage pumps clearing road ponding; smooth transit flow.',
      actionRecommendation: 'Safe delayed transit window. Roadways drained and vehicular traffic returned to normal pace.',
      verdictBadge: 'SAFE DELAYED WINDOW',
      isRecommended: false,
    },
    {
      slotKey: 'tomorrow',
      departureLabel: 'Kal Subah (Tomorrow 07:30 AM)',
      timeSubtitle: 'Next day: 07:30 AM',
      rainProbability: 10,
      temperature: 24,
      windSpeed: 10,
      delayMins: '0 mins (On-time)',
      delayRisk: 'Low',
      waterloggingSeverity: 'None (Completely dry corridors)',
      lightningHazard: 'Zero risk',
      summary: 'Clear morning skies with pleasant ambient temperatures and dry national highway corridors.',
      actionRecommendation: 'Best overall choice if travel is non-urgent. Maximum fuel economy and comfortable driving conditions.',
      verdictBadge: 'OPTIMAL NON-URGENT DEPARTURE',
      isRecommended: false,
    }
  ];
};

export const POPULAR_ROUTES = [
  { origin: 'Connaught Place, Central Delhi', destination: 'Cyber City, Gurugram' },
  { origin: 'Noida Electronic City, Sec 62', destination: 'IGI Airport Terminal 3' },
  { origin: 'New Delhi Railway Station', destination: 'Karnal Agri Hub (NH-44)' },
  { origin: 'Pune Station', destination: 'Hinjawadi IT Park' },
];

export const calculateRouteWeather = (
  origin: string,
  destination: string
): { checkpoints: RouteCheckpoint[]; totalDistanceKm: number; estimatedDurationMins: number; routeAlert?: string } => {
  // Checkpoints along representative Delhi-Gurugram highway corridor or generic corridor
  const checkpoints: RouteCheckpoint[] = [
    {
      id: 'cp-1',
      name: origin || 'Connaught Place, Delhi',
      distanceKm: 0,
      eta: '00 mins',
      temperature: 31,
      condition: 'Overcast & Drizzle',
      conditionCode: 'rain',
      rainProbability: 65,
      windSpeed: 22,
      hazardNote: 'Wet asphalt; moderate surface spray',
      isHazardous: false,
    },
    {
      id: 'cp-2',
      name: 'Dhaula Kuan Junction Flyover',
      distanceKm: 9.2,
      eta: '+18 mins',
      temperature: 30,
      condition: 'Heavy Downpour',
      conditionCode: 'rain',
      rainProbability: 85,
      windSpeed: 34,
      hazardNote: 'Caution: Slow-moving traffic & gusty crosswinds on flyover',
      isHazardous: true,
    },
    {
      id: 'cp-3',
      name: 'Mahipalpur / Aerocity Underpass',
      distanceKm: 18.5,
      eta: '+34 mins',
      temperature: 29,
      condition: 'Intense Rain & Low Visibility',
      conditionCode: 'thunderstorm',
      rainProbability: 92,
      windSpeed: 38,
      hazardNote: 'Water pooling alert near underpass exit ramp; visibility < 2.0 km',
      isHazardous: true,
    },
    {
      id: 'cp-4',
      name: 'Sirhaul Border (Delhi-Haryana)',
      distanceKm: 24.8,
      eta: '+46 mins',
      temperature: 30,
      condition: 'Moderate Rain Showers',
      conditionCode: 'rain',
      rainProbability: 78,
      windSpeed: 28,
      hazardNote: 'Toll bottleneck; road surface wet but draining smoothly',
      isHazardous: false,
    },
    {
      id: 'cp-5',
      name: destination || 'Cyber City, Gurugram',
      distanceKm: 31.4,
      eta: '+58 mins',
      temperature: 30,
      condition: 'Light Rain & Overcast',
      conditionCode: 'rain',
      rainProbability: 70,
      windSpeed: 24,
      hazardNote: 'Destination approach normal; sheltered basement parking accessible',
      isHazardous: false,
    },
  ];

  return {
    checkpoints,
    totalDistanceKm: 31.4,
    estimatedDurationMins: 58,
    routeAlert: 'Route Weather Alert: Severe convective rain cell detected between km 15–22 (Aerocity to Sirhaul corridor). Expect 15–20 min delay.',
  };
};
